"""Generate the recipe atlas page.

One page with every recipe in the pack, grouped by module and indexed by name, so a
player looking for something has a single place to look. Generated rather than
written, because a hand-kept list of 58 recipes drifts the moment one is added: the
names come out of the recipes themselves.
"""

import json
import os

# Module title and doc page per namespace. A namespace missing from here still gets
# a section, titled after itself.
MODULES = {
    "ra": ("Tools", "index.md"),
    "ra_gates": ("Logic Gates", "logic-gates.md"),
    "ra_interactive": ("Interactive Machines", "interactive-machines.md"),
    "ra_storage": ("Storage", "storage.md"),
    "ra_sensors": ("Sensors", "sensors.md"),
    "ra_wireless": ("Wireless Redstone", "wireless-redstone.md"),
    "ra_wires": ("Transport Networks", "transport-networks.md"),
    "ra_chunk_loader": ("Chunk Loader", "chunk-loader.md"),
    "ra_multiblock": ("Multiblocks", "multiblocks.md"),
    "ra_infinite": ("Infinite Generators", "infinite-generators.md"),
    "ra_jetpacks": ("Jetpacks", "jetpacks.md"),
    "ra_ender": ("Ender Links", "ender-links.md"),
}

GIVE = {
    "ra": "/function ra:tools/give_all",
    "ra_gates": "/function ra_gates:items/give_all",
    "ra_interactive": "/function ra_interactive:items/give_all",
    "ra_storage": "/function ra_storage:items/give_all",
    "ra_sensors": "/function ra_sensors:items/give_all",
    "ra_wireless": "/function ra_wireless:items/give_all",
    "ra_wires": "/function ra_wires:items/give_all",
    "ra_chunk_loader": "/function ra_chunk_loader:items/give_all",
    "ra_multiblock": "/function ra_multiblock:blocks/give_all",
    "ra_infinite": "/function ra_infinite:items/give_all",
    "ra_jetpacks": "/function ra_jetpacks:items/give_all",
    "ra_ender": "/function ra_ender:items/give_all",
}

TYPE_NAMES = {
    "minecraft:crafting_shaped": "Crafting table",
    "minecraft:crafting_shapeless": "Crafting table, shapeless",
    "minecraft:crafting_transmute": "Crafting table",
    "minecraft:smelting": "Furnace",
    "minecraft:blasting": "Blast furnace",
    "minecraft:smoking": "Smoker",
    "minecraft:campfire_cooking": "Campfire",
    "minecraft:stonecutting": "Stonecutter",
    "minecraft:smithing_transform": "Smithing table",
    "minecraft:smithing_trim": "Smithing table",
}


def collect(pack_src, images_root, docs_root):
    """Every recipe as (namespace, name, display name, station, image path)."""
    out = []
    for namespace in sorted(os.listdir(pack_src)):
        folder = os.path.join(pack_src, namespace, "recipe")
        if not os.path.isdir(folder):
            continue
        for file in sorted(os.listdir(folder)):
            if not file.endswith(".json"):
                continue
            name = file[:-5]
            data = json.load(open(os.path.join(folder, file)))
            result = data.get("result")
            result = {"id": result} if isinstance(result, str) else (result or {})
            components = result.get("components") or {}
            display = components.get("minecraft:item_name") or result.get("id", name).split(":")[-1].replace("_", " ").title()
            image = os.path.join("images", "recipes", namespace, name + ".png")
            if not os.path.isfile(os.path.join(docs_root, image)):
                image = None
            out.append((namespace, name, display, TYPE_NAMES.get(data.get("type"), "Special"), image))
    return out


def write(rows, target, docs_root):
    lines = [
        "# Recipe Atlas",
        "",
        "Every recipe in the pack, in one place: " + str(len(rows)) + " of them.",
        "",
        "!!! tip \"Finding one\"",
        "    Use the search box with the item's name — every recipe below is indexed by",
        "    it. The table right underneath is the same list alphabetically, and each",
        "    module section links to the page explaining what those blocks do.",
        "",
        "This page is generated by `tools/recipe_render/render.py --atlas`, so it lists",
        "what the pack actually contains rather than what someone remembered to add.",
        "",
        "## Every item, A to Z",
        "",
        "| Item | Module | Station |",
        "| ---- | ------ | ------- |",
    ]

    for namespace, name, display, station, image in sorted(rows, key=lambda r: r[2].lower()):
        title, page = MODULES.get(namespace, (namespace, None))
        anchor = "#" + title.lower().replace(" ", "-")
        lines.append("| [%s](%s) | [%s](%s) | %s |" % (display, anchor, title, page or anchor, station))

    by_module = {}
    for row in rows:
        by_module.setdefault(row[0], []).append(row)

    for namespace in sorted(by_module, key=lambda n: MODULES.get(n, (n,))[0]):
        title, page = MODULES.get(namespace, (namespace, None))
        lines += ["", "## " + title, ""]
        if page:
            lines.append("Module page: [%s](%s) — give everything: `%s`" % (title, page, GIVE.get(namespace, "n/a")))
            lines.append("")
        lines += ["| Item | Recipe | Station | Namespace id |", "| ---- | ------ | ------- | ------------ |"]
        for _, name, display, station, image in sorted(by_module[namespace], key=lambda r: r[2].lower()):
            picture = "![%s recipe](%s){ width=\"220\" }" % (display, image) if image else "_no picture yet_"
            lines.append("| **%s** | %s | %s | `%s:%s` |" % (display, picture, station, namespace, name))

    lines.append("")
    pathlib_target = os.path.join(docs_root, target)
    open(pathlib_target, "w").write("\n".join(lines))
    return pathlib_target
