"""Beet plugin that generates the Redstone Additions settings system.

WHY THIS IS GENERATED AND NOT HAND-WRITTEN
Operator settings are reached with /function, so that they autocomplete: typing
`/function ra_settings:admin/` and pressing tab walks the whole tree. Autocomplete
is the only discovery mechanism a command has, and it only works on real function
paths -- a macro argument like {key:"...",value:5} completes to nothing, and the
admin has to already know the key to type it.

That means one function per setting per action, which is far too many to maintain
by hand and would drift from the runtime registry the moment either changed. So
both come out of the same JSON: tools/settings/<page>.json.

The other benefit is that the generator knows every key, bound and step as a
literal at build time, so the emitted commands need no macros. Nothing here has
to survive a player-authored quote character being substituted into a command.

PAGE FILES
    {"id","title","namespace","rows":[...]}
Row types: bool, int, list  (each scope "global" or "user"),
           block (enable/disable a placeable),
           prop  (default for a per-block property, seeded at placement).

Global rows generate an admin function tree and no menu entry. User rows generate
a menu entry and no admin function -- a player changes their own with /trigger,
which needs no permissions, and an operator has no business setting it for them.
"""

import json
from beet import Context, Function, FunctionTag

DEFS = "tools/settings"
ADMIN = "ra_settings:admin"

BAR = '[{text:"─── ",color:"dark_gray"},{text:"%s",color:"gold",bold:true},{text:" ───",color:"dark_gray"}]'


def gpath(key):
    """Storage path for a global key. Always quoted -- keys contain dots, and an
    unquoted dot is a path separator, so `wires.rate` would silently become a
    nested compound instead of one key."""
    return f'global."{key}"'


def ppath(block, prop):
    return f'global.props."{block}"."{prop}"'


def esc(path):
    """A path being embedded INSIDE a quoted SNBT string.

    Keys are quoted in the path itself (they contain dots), and those quotes have
    to be escaped again once the whole path becomes the value of `nbt:"..."`.
    Without this the component ends early and the rest of the path leaks out as
    stray tokens -- valid-looking text that parses as garbage."""
    return path.replace('"', '\\"')


def report(label, path, extra=""):
    return (
        f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},'
        f'{{text:" is now ",color:"gray"}},{{nbt:"{esc(path)}",storage:"ra:settings",color:"aqua"}}{extra}]'
    )


def clamp_write(path, lo, hi):
    """Step arithmetic lands in #n; clamp it and store it back."""
    return [
        f"execute if score #n ra.set.tmp matches ..{lo - 1} run scoreboard players set #n ra.set.tmp {lo}",
        f"execute if score #n ra.set.tmp matches {hi + 1}.. run scoreboard players set #n ra.set.tmp {hi}",
        f"execute store result storage ra:settings {path} int 1 run scoreboard players get #n ra.set.tmp",
    ]


def read_into_n(path, default):
    return [
        f"scoreboard players set #n ra.set.tmp {default}",
        f"execute if data storage ra:settings {path} store result score #n ra.set.tmp run data get storage ra:settings {path}",
    ]


def beet_default(ctx: Context):
    root = ctx.directory / DEFS
    pages = [json.loads(p.read_text()) for p in sorted(root.glob("*.json"))]

    defaults = [
        "# Generated by tools/settings_gen.py -- do not edit.",
        "# Seeds every declared setting that has no value yet. Runs on every load, so",
        "# it must never overwrite: `unless data` is what makes it a seed and not a reset.",
        "",
        "execute unless data storage ra:settings global run data modify storage ra:settings global set value {}",
        "execute unless data storage ra:settings disabled run data modify storage ra:settings disabled set value []",
        "execute unless data storage ra:settings users run data modify storage ra:settings users set value []",
        "",
    ]
    menu_pages = []
    admin_index = []
    user_seed = []

    # Every clickable admin action, in order. The button carries the index; the
    # dispatcher looks the path back up here and runs it. Keeping the paths in one
    # list is what lets a button be a /trigger while the same action stays a real
    # autocompleting function.
    actions = []

    def act(fn):
        actions.append(fn)
        return len(actions)  # 1-based: /trigger cannot deliver 0

    for page in pages:
        pid, title = page["id"], page["title"]
        user_rows = []
        admin_rows = []

        for row in page["rows"]:
            t = row["type"]
            scope = row.get("scope")

            if scope == "user":
                defaults.append(f'scoreboard objectives add {row["obj"]} dummy')
                if row["type"] in ("bool", "int", "list"):
                    user_seed.append(row)
                user_rows.append(row)
                continue

            admin_rows.append(row)

            if t == "block":
                block, label = row["block"], row["label"]
                base = f'{ADMIN}/{pid}/{_slug(label)}'
                ctx.data.functions[f"{base}/enable"] = Function([
                    f"# Allow {label} to be placed again.",
                    f'data remove storage ra:settings disabled[{{b:"{block}"}}]',
                    f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" enabled.",color:"green"}}]',
                ])
                ctx.data.functions[f"{base}/disable"] = Function([
                    f"# Stop {label} being placed. Blocks already in the world keep working --",
                    f"# deleting somebody's build because a box was ticked is not a setting.",
                    f'execute unless data storage ra:settings disabled[{{b:"{block}"}}] run data modify storage ra:settings disabled append value {{b:"{block}"}}',
                    f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" disabled — existing ones keep working.",color:"red"}}]',
                ])
                continue

            if t == "prop":
                block, prop, label = row["block"], row["prop"], row["label"]
                path, dflt = ppath(block, prop), row["default"]
                lo, hi, step = row["min"], row["max"], row["step"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                base = f'{ADMIN}/{pid}/{_slug(label)}'
                note = ',{text:" (new blocks only)",color:"dark_gray"}'
                for name, delta in (("up", step), ("down", -step)):
                    verb = "add" if delta > 0 else "remove"
                    ctx.data.functions[f"{base}/{name}"] = Function(
                        [f"# {label}: {name} by {step}. Applies to blocks placed from now on."]
                        + read_into_n(path, dflt)
                        + [f"scoreboard players {verb} #n ra.set.tmp {abs(delta)}"]
                        + clamp_write(path, lo, hi)
                        + [report(label, path, note)]
                    )
                ctx.data.functions[f"{base}/reset"] = Function([
                    f"# {label}: back to the shipped default of {dflt}.",
                    f"data modify storage ra:settings {path} set value {dflt}",
                    report(label, path, note),
                ])
                # Stepping alone is not enough for a wide range: moving a
                # generator from 60 to 500 EU would be forty-four clicks.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type an exact value ({lo}-{hi}).",
                    f'data modify storage ra:settings admin_edit set value '
                    f'{{block:"{block}",prop:"{prop}",type:"int",min:{lo},max:{hi}}}',
                    "function ra_settings:admin_edit_start",
                ])
                continue

            key, label = row["key"], row["label"]
            path = gpath(key)
            base = f'{ADMIN}/{pid}/{_slug(label)}'

            if t == "bool":
                dflt = row["default"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}b'
                )
                for name, val in (("on", 1), ("off", 0)):
                    ctx.data.functions[f"{base}/{name}"] = Function([
                        f"# {label}: {name}.",
                        f"data modify storage ra:settings {path} set value {val}b",
                        report(label, path),
                    ])

            elif t == "int":
                dflt, lo, hi, step = row["default"], row["min"], row["max"], row["step"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                for name, delta in (("up", step), ("down", -step)):
                    verb = "add" if delta > 0 else "remove"
                    ctx.data.functions[f"{base}/{name}"] = Function(
                        [f"# {label}: {name} by {step}."]
                        + read_into_n(path, dflt)
                        + [f"scoreboard players {verb} #n ra.set.tmp {abs(delta)}"]
                        + clamp_write(path, lo, hi)
                        + [report(label, path)]
                    )
                ctx.data.functions[f"{base}/reset"] = Function([
                    f"# {label}: back to the shipped default of {dflt}.",
                    f"data modify storage ra:settings {path} set value {dflt}",
                    report(label, path),
                ])
                # Stepping is one click; typing is for when the target is far from
                # where the value currently sits.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type an exact value ({lo}-{hi}).",
                    f'data modify storage ra:settings admin_edit set value {{key:"{key}",type:"int",min:{lo},max:{hi}}}',
                    "function ra_settings:admin_edit_start",
                ])

            elif t == "str":
                dflt = row.get("default", "")
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value "{dflt}"'
                )
                # Text has nothing to step, so there is no up/down -- only typing
                # it, through the same input form the Data Handler opens.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type a new value.",
                    f'data modify storage ra:settings admin_edit set value {{key:"{key}",type:"str"}}',
                    "function ra_settings:admin_edit_start",
                ])
                ctx.data.functions[f"{base}/reset"] = Function([
                    f'# {label}: back to the shipped default.',
                    f'data modify storage ra:settings {path} set value "{dflt}"',
                    report(label, path),
                ])

            elif t == "list":
                values, dflt = row["values"], row["default"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                # One function per choice, so the choices themselves autocomplete.
                # The stored value stays the INDEX -- renaming a choice then moves
                # the label without orphaning what anybody had selected.
                for i, choice in enumerate(values):
                    ctx.data.functions[f"{base}/{_slug(choice)}"] = Function([
                        f"# {label}: {choice}.",
                        f"data modify storage ra:settings {path} set value {i}",
                        f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" is now ",color:"gray"}},{{text:"{choice}",color:"aqua"}}]',
                    ])

        # Per-page overview, and the page's entry in the admin index.
        if admin_rows:
            ctx.data.functions[f"{ADMIN}/{pid}/show"] = Function(
                [f"# Current values on the {title} page.", f"tellraw @s {BAR % title}"]
                + [ln for r in admin_rows for ln in _show_line(r, f"{ADMIN}/{pid}", act)]
                + [
                    'tellraw @s [{text:""}]',
                    'tellraw @s [{text:"  "},'
                    + _btn("Back", f"{ADMIN}/show", "gray",
                           "Back to all server settings", act(f"{ADMIN}/show"))
                    + "]",
                ]
            )
            admin_index.append((pid, title))

        if user_rows:
            menu_pages.append({"id": pid, "title": title, "rows": user_rows})

    # The registry the /trigger menu renders from. User rows only: operator
    # settings are not in the menu at all, so there is nothing there for a player
    # to click and be refused.
    ctx.data.functions["ra_settings:pages"] = Function(
        [
            "# Generated by tools/settings_gen.py -- do not edit.",
            "# The pages the in-game menu shows. Only user-scope rows appear here;",
            "# operator settings live in the /function ra_settings:admin tree.",
            "",
            "data modify storage ra:settings pages set value []",
        ]
        + [
            f"data modify storage ra:settings pages append value {_snbt(p)}"
            for p in menu_pages
        ]
    )

    ctx.data.functions["ra_settings:defaults"] = Function(defaults)

    # Every tick, give any player who has no score on a user setting its default.
    #
    # This is what makes the gated selectors work at all. A player who has never
    # opened the menu has no score, and an ABSENT score fails every comparison --
    # so @a[scores={ra.u.snd=1..}] would exclude them and they would hear nothing.
    # Seeding at load would not do: players join later than load.
    ctx.data.functions["ra_settings:sync"] = Function(
        [
            "# Generated by tools/settings_gen.py -- do not edit.",
            "# Seeds user settings for players who have none. See settings_gen.py.",
        ]
        + [
            f"execute as @a unless score @s {r['obj']} matches -2147483648.. "
            f"run scoreboard players set @s {r['obj']} {r['default']}"
            for r in user_seed
        ]
    )

    ctx.data.functions[f"{ADMIN}/show"] = Function(
        [
            "# The server settings index. Context: as an operator.",
            "#",
            "# Opening this is what grants ra.admin, so every button below can be a",
            "# /trigger instead of a /function and stop raising a confirmation prompt on",
            "# each click. Reaching this function at all needs permission level 2, so the",
            "# tag cannot be obtained any other way -- see ra_settings:admin_grant.",
            "function ra_settings:admin_grant",
            "",
            f"tellraw @s {BAR % 'Redstone Additions — Server Settings'}",
        ]
        + [
            f'tellraw @s [{{text:"  "}},'
            + _btn(t, f"{ADMIN}/{p}/show", "yellow", f"Open {t}", act(f"{ADMIN}/{p}/show"))
            + "]"
            for p, t in admin_index
        ]
        + [
            'tellraw @s [{text:""}]',
            'tellraw @s [{text:"  "},'
            + _btn("Uninstall", "ra:uninstall", "dark_red",
                   "Remove Redstone Additions from this world", act("ra:uninstall"))
            + "]",
            'tellraw @s [{text:"Players change their own preferences with ",color:"gray"},'
            '{text:"/trigger ra.settings.open",color:"yellow"},{text:" — no operator needed.",color:"gray"}]',
        ]
    )

    # Uninstall, generated so it cannot drift from what was created. Every
    # objective this system adds is listed above in `defaults`; hand-maintaining a
    # second copy is how the old uninstall ended up missing half of them.
    ctx.data.functions["ra_settings:uninstall"] = Function(
        [
            "# Generated by tools/settings_gen.py -- do not edit.",
            "# Remove everything ra_settings created. Called from ra:uninstall/confirm.",
        ]
        + [f"scoreboard objectives remove {o}" for o in sorted({r["obj"] for r in user_seed})]
        + [
            "scoreboard objectives remove ra.settings.open",
            "scoreboard objectives remove ra.settings.act",
            "scoreboard objectives remove ra.settings.admin",
            "scoreboard objectives remove ra.settings.page",
            "scoreboard objectives remove ra.settings.pend",
            "scoreboard objectives remove ra.admin.ttl",
            "scoreboard objectives remove ra.set.tmp",
            "data remove storage ra:settings {}",
            "tag @a remove ra.admin",
        ]
    )

    # The dispatch table. A macro runs the path, so this is one command rather than
    # a comparison per action.
    ctx.data.functions["ra_settings:admin_actions"] = Function(
        [
            "# Generated by tools/settings_gen.py -- do not edit.",
            "# Index -> function path for every clickable server-settings action.",
            "data modify storage ra:settings actions set value ["
            + ",".join(f'"{a}"' for a in actions)
            + "]",
        ]
    )

    ctx.data.function_tags["ra_settings:register"] = FunctionTag(
        {"values": ["ra_settings:pages", "ra_settings:defaults", "ra_settings:admin_actions"]}
    )


def _slug(text):
    """A function-path segment. Only [a-z0-9_] survives, because a resource
    location rejects spaces, capitals and punctuation outright."""
    out = "".join(c if c.isalnum() else "_" for c in str(text).lower())
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_")


def _show_line(row, base, act):
    """One row of a page overview: the value, then the buttons that change it.

    The overview used to print values only, which meant reading a setting here
    and then typing its full path somewhere else to change it. Everything on
    these pages is operator-only anyway -- they are reached through /function --
    so the buttons cost nothing and remove the retyping."""
    label = row["label"]
    t = row["type"]
    slug = f"{base}/{_slug(label)}"

    if t == "block":
        block = row["block"]
        on = (f'{{text:"  {label}: ",color:"white"}},{{text:"enabled ",color:"green"}},'
              + _btn("Disable", f"{slug}/disable", "red", f"Stop {label} being placed", act(f"{slug}/disable")))
        off = (f'{{text:"  {label}: ",color:"white"}},{{text:"disabled ",color:"red"}},'
               + _btn("Enable", f"{slug}/enable", "green", f"Allow {label} again", act(f"{slug}/enable")))
        return [
            f'execute unless data storage ra:settings disabled[{{b:"{block}"}}] run tellraw @s [{on}]',
            f'execute if data storage ra:settings disabled[{{b:"{block}"}}] run tellraw @s [{off}]',
        ]

    if t == "prop":
        path = ppath(row["block"], row["prop"])
    else:
        path = gpath(row["key"])

    head = (f'{{text:"  {label}: ",color:"white"}},'
            f'{{nbt:"{esc(path)}",storage:"ra:settings",color:"aqua"}},{{text:"  "}}')

    if t == "bool":
        btns = _btn("On", f"{slug}/on", "green", None, act(f"{slug}/on")) + ',{text:" "},' + _btn("Off", f"{slug}/off", "red", None, act(f"{slug}/off"))
    elif t in ("int", "prop"):
        btns = (_btn("-", f"{slug}/down", "red", f'Down by {row["step"]}', act(f"{slug}/down")) + ',{text:" "},'
                + _btn("+", f"{slug}/up", "green", f'Up by {row["step"]}', act(f"{slug}/up")) + ',{text:" "},'
                + _btn("Set", f"{slug}/edit", "yellow", "Type an exact value", act(f"{slug}/edit")) + ',{text:" "},'
                + _btn("Reset", f"{slug}/reset", "gray", None, act(f"{slug}/reset")))
    elif t == "str":
        btns = (_btn("Set", f"{slug}/edit", "yellow", "Type a new value", act(f"{slug}/edit")) + ',{text:" "},'
                + _btn("Reset", f"{slug}/reset", "gray", None, act(f"{slug}/reset")))
    elif t == "list":
        btns = ",{text:\" \"},".join(
            _btn(c, f"{slug}/{_slug(c)}", "yellow", None, act(f"{slug}/{_slug(c)}")) for c in row["values"])
    else:
        btns = '{text:""}'

    return [f'tellraw @s [{head},{btns}]']


def _btn(text, fn, color, hover=None, code=None):
    """A menu button.

    Fires /trigger rather than the action's /function. Both reach the same code --
    the function tree still exists and still autocompletes -- but a run_command
    click event raises a confirmation prompt every single time, and an operator
    stepping a value ten times should not answer ten dialogs. /trigger is exempt
    because the game already knows a trigger is safe: it only writes a score the
    player was explicitly enabled for.

    The permission check moves with it. See ra_settings:admin_dispatch."""
    hover = hover or f"/function {fn}"
    cmd = f"/trigger ra.settings.admin set {code}" if code is not None else f"/function {fn}"
    return (f'{{text:"[{text}]",color:"{color}",bold:true,'
            f'hover_event:{{action:"show_text",value:"{hover}"}},'
            f'click_event:{{action:"run_command",command:"{cmd}"}}}}')


def _snbt(obj):
    """JSON is not SNBT: SNBT keys are bare and its strings are double-quoted."""
    if isinstance(obj, dict):
        return "{" + ",".join(f"{k}:{_snbt(v)}" for k, v in obj.items()) + "}"
    if isinstance(obj, list):
        return "[" + ",".join(_snbt(v) for v in obj) + "]"
    if isinstance(obj, bool):
        return "1b" if obj else "0b"
    if isinstance(obj, str):
        return json.dumps(obj)
    return str(obj)
