"""Beet plugin that generates the Redstone Additions settings system.

WHY THIS IS GENERATED AND NOT HAND-WRITTEN
Operator settings are reached with /function, so that they autocomplete: typing
`/function ra_settings:admin/` and pressing tab walks the whole tree. Autocomplete
is the only discovery mechanism a command has, and it only works on real function
paths -- a macro argument like {key:"...",value:5} completes to nothing, and the
admin has to already know the key to type it.

That means one function per setting per action, which is far too many to maintain
by hand and would drift from the runtime registry the moment either changed. So
both come out of the same JSON: tools/settings/<page>.json.

The other benefit is that the generator knows every key, bound and step as a
literal at build time, so the emitted commands need no macros. Nothing here has
to survive a player-authored quote character being substituted into a command.

PAGE FILES
    {"id","title","namespace","rows":[...]}
Row types: bool, int, list  (each scope "global" or "user"),
           block (enable/disable a placeable),
           prop  (default for a per-block property, seeded at placement).

Global rows generate an admin function tree and no menu entry. User rows generate
a menu entry and no admin function -- a player changes their own with /trigger,
which needs no permissions, and an operator has no business setting it for them.
"""

import json
from beet import Context, Function, FunctionTag

DEFS = "tools/settings"
ADMIN = "ra_settings:admin"

BAR = '[{text:"─── ",color:"dark_gray"},{text:"%s",color:"gold",bold:true},{text:" ───",color:"dark_gray"}]'


def gpath(key):
    """Storage path for a global key. Always quoted -- keys contain dots, and an
    unquoted dot is a path separator, so `wires.rate` would silently become a
    nested compound instead of one key."""
    return f'global."{key}"'


def ppath(block, prop):
    return f'global.props."{block}"."{prop}"'


def esc(path):
    """A path being embedded INSIDE a quoted SNBT string.

    Keys are quoted in the path itself (they contain dots), and those quotes have
    to be escaped again once the whole path becomes the value of `nbt:"..."`.
    Without this the component ends early and the rest of the path leaks out as
    stray tokens -- valid-looking text that parses as garbage."""
    return path.replace('"', '\\"')


def report(label, path, extra=""):
    return (
        f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},'
        f'{{text:" is now ",color:"gray"}},{{nbt:"{esc(path)}",storage:"ra:settings",color:"aqua"}}{extra}]'
    )


def clamp_write(path, lo, hi):
    """Step arithmetic lands in #n; clamp it and store it back."""
    return [
        f"execute if score #n ra.set.tmp matches ..{lo - 1} run scoreboard players set #n ra.set.tmp {lo}",
        f"execute if score #n ra.set.tmp matches {hi + 1}.. run scoreboard players set #n ra.set.tmp {hi}",
        f"execute store result storage ra:settings {path} int 1 run scoreboard players get #n ra.set.tmp",
    ]


def read_into_n(path, default):
    return [
        f"scoreboard players set #n ra.set.tmp {default}",
        f"execute if data storage ra:settings {path} store result score #n ra.set.tmp run data get storage ra:settings {path}",
    ]


def beet_default(ctx: Context):
    root = ctx.directory / DEFS
    pages = [json.loads(p.read_text()) for p in sorted(root.glob("*.json"))]

    defaults = [
        "# Generated by tools/settings_gen.py -- do not edit.",
        "# Seeds every declared setting that has no value yet. Runs on every load, so",
        "# it must never overwrite: `unless data` is what makes it a seed and not a reset.",
        "",
        "execute unless data storage ra:settings global run data modify storage ra:settings global set value {}",
        "execute unless data storage ra:settings disabled run data modify storage ra:settings disabled set value []",
        "execute unless data storage ra:settings users run data modify storage ra:settings users set value []",
        "",
    ]
    menu_pages = []
    admin_index = []

    for page in pages:
        pid, title = page["id"], page["title"]
        user_rows = []
        admin_rows = []

        for row in page["rows"]:
            t = row["type"]
            scope = row.get("scope")

            if scope == "user":
                defaults.append(f'scoreboard objectives add {row["obj"]} dummy')
                user_rows.append(row)
                continue

            admin_rows.append(row)

            if t == "block":
                block, label = row["block"], row["label"]
                base = f'{ADMIN}/{pid}/{_slug(label)}'
                ctx.data.functions[f"{base}/enable"] = Function([
                    f"# Allow {label} to be placed again.",
                    f'data remove storage ra:settings disabled[{{b:"{block}"}}]',
                    f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" enabled.",color:"green"}}]',
                ])
                ctx.data.functions[f"{base}/disable"] = Function([
                    f"# Stop {label} being placed. Blocks already in the world keep working --",
                    f"# deleting somebody's build because a box was ticked is not a setting.",
                    f'execute unless data storage ra:settings disabled[{{b:"{block}"}}] run data modify storage ra:settings disabled append value {{b:"{block}"}}',
                    f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" disabled — existing ones keep working.",color:"red"}}]',
                ])
                continue

            if t == "prop":
                block, prop, label = row["block"], row["prop"], row["label"]
                path, dflt = ppath(block, prop), row["default"]
                lo, hi, step = row["min"], row["max"], row["step"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                base = f'{ADMIN}/{pid}/{_slug(label)}'
                note = ',{text:" (new blocks only)",color:"dark_gray"}'
                for name, delta in (("up", step), ("down", -step)):
                    verb = "add" if delta > 0 else "remove"
                    ctx.data.functions[f"{base}/{name}"] = Function(
                        [f"# {label}: {name} by {step}. Applies to blocks placed from now on."]
                        + read_into_n(path, dflt)
                        + [f"scoreboard players {verb} #n ra.set.tmp {abs(delta)}"]
                        + clamp_write(path, lo, hi)
                        + [report(label, path, note)]
                    )
                ctx.data.functions[f"{base}/reset"] = Function([
                    f"# {label}: back to the shipped default of {dflt}.",
                    f"data modify storage ra:settings {path} set value {dflt}",
                    report(label, path, note),
                ])
                # Stepping alone is not enough for a wide range: moving a
                # generator from 60 to 500 EU would be forty-four clicks.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type an exact value ({lo}-{hi}).",
                    f'data modify storage ra:settings admin_edit set value '
                    f'{{block:"{block}",prop:"{prop}",type:"int",min:{lo},max:{hi}}}',
                    "function ra_settings:admin_edit_start",
                ])
                continue

            key, label = row["key"], row["label"]
            path = gpath(key)
            base = f'{ADMIN}/{pid}/{_slug(label)}'

            if t == "bool":
                dflt = row["default"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}b'
                )
                for name, val in (("on", 1), ("off", 0)):
                    ctx.data.functions[f"{base}/{name}"] = Function([
                        f"# {label}: {name}.",
                        f"data modify storage ra:settings {path} set value {val}b",
                        report(label, path),
                    ])

            elif t == "int":
                dflt, lo, hi, step = row["default"], row["min"], row["max"], row["step"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                for name, delta in (("up", step), ("down", -step)):
                    verb = "add" if delta > 0 else "remove"
                    ctx.data.functions[f"{base}/{name}"] = Function(
                        [f"# {label}: {name} by {step}."]
                        + read_into_n(path, dflt)
                        + [f"scoreboard players {verb} #n ra.set.tmp {abs(delta)}"]
                        + clamp_write(path, lo, hi)
                        + [report(label, path)]
                    )
                ctx.data.functions[f"{base}/reset"] = Function([
                    f"# {label}: back to the shipped default of {dflt}.",
                    f"data modify storage ra:settings {path} set value {dflt}",
                    report(label, path),
                ])
                # Stepping is one click; typing is for when the target is far from
                # where the value currently sits.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type an exact value ({lo}-{hi}).",
                    f'data modify storage ra:settings admin_edit set value {{key:"{key}",type:"int",min:{lo},max:{hi}}}',
                    "function ra_settings:admin_edit_start",
                ])

            elif t == "str":
                dflt = row.get("default", "")
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value "{dflt}"'
                )
                # Text has nothing to step, so there is no up/down -- only typing
                # it, through the same input form the Data Handler opens.
                ctx.data.functions[f"{base}/edit"] = Function([
                    f"# {label}: type a new value.",
                    f'data modify storage ra:settings admin_edit set value {{key:"{key}",type:"str"}}',
                    "function ra_settings:admin_edit_start",
                ])
                ctx.data.functions[f"{base}/reset"] = Function([
                    f'# {label}: back to the shipped default.',
                    f'data modify storage ra:settings {path} set value "{dflt}"',
                    report(label, path),
                ])

            elif t == "list":
                values, dflt = row["values"], row["default"]
                defaults.append(
                    f'execute unless data storage ra:settings {path} run data modify storage ra:settings {path} set value {dflt}'
                )
                # One function per choice, so the choices themselves autocomplete.
                # The stored value stays the INDEX -- renaming a choice then moves
                # the label without orphaning what anybody had selected.
                for i, choice in enumerate(values):
                    ctx.data.functions[f"{base}/{_slug(choice)}"] = Function([
                        f"# {label}: {choice}.",
                        f"data modify storage ra:settings {path} set value {i}",
                        f'tellraw @s [{{text:"[Settings] ",color:"gold"}},{{text:"{label}",color:"white"}},{{text:" is now ",color:"gray"}},{{text:"{choice}",color:"aqua"}}]',
                    ])

        # Per-page overview, and the page's entry in the admin index.
        if admin_rows:
            ctx.data.functions[f"{ADMIN}/{pid}/show"] = Function(
                [f"# Current values on the {title} page.", f"tellraw @s {BAR % title}"]
                + [ln for r in admin_rows for ln in _show_line(r)]
            )
            admin_index.append((pid, title))

        if user_rows:
            menu_pages.append({"id": pid, "title": title, "rows": user_rows})

    # The registry the /trigger menu renders from. User rows only: operator
    # settings are not in the menu at all, so there is nothing there for a player
    # to click and be refused.
    ctx.data.functions["ra_settings:pages"] = Function(
        [
            "# Generated by tools/settings_gen.py -- do not edit.",
            "# The pages the in-game menu shows. Only user-scope rows appear here;",
            "# operator settings live in the /function ra_settings:admin tree.",
            "",
            "data modify storage ra:settings pages set value []",
        ]
        + [
            f"data modify storage ra:settings pages append value {_snbt(p)}"
            for p in menu_pages
        ]
    )

    ctx.data.functions["ra_settings:defaults"] = Function(defaults)

    ctx.data.functions[f"{ADMIN}/show"] = Function(
        [
            "# Every operator settings page, and how to reach it.",
            "#",
            "# The paths are printed as clickable suggestions as well as text, because the",
            "# point of the function tree is that it autocompletes -- this puts the first",
            "# segment in the chat box so tab does the rest.",
            f"tellraw @s {BAR % 'Redstone Additions — Operator Settings'}",
        ]
        + [
            f'tellraw @s [{{text:"  {t}: ",color:"white"}},{{text:"/function {ADMIN}/{p}/show",color:"yellow",'
            f'hover_event:{{action:"show_text",value:"Show current values"}},'
            f'click_event:{{action:"suggest_command",command:"/function {ADMIN}/{p}/"}}}}]'
            for p, t in admin_index
        ]
        + [
            'tellraw @s [{text:"Players change their own preferences with ",color:"gray"},'
            '{text:"/trigger ra.settings.open set 1",color:"yellow"},{text:" — no operator needed.",color:"gray"}]'
        ]
    )

    ctx.data.function_tags["ra_settings:register"] = FunctionTag(
        {"values": ["ra_settings:pages", "ra_settings:defaults"]}
    )


def _slug(text):
    """A function-path segment. Only [a-z0-9_] survives, because a resource
    location rejects spaces, capitals and punctuation outright."""
    out = "".join(c if c.isalnum() else "_" for c in str(text).lower())
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_")


def _show_line(row):
    """One row of a page overview, as a list of lines.

    A block row needs two: the stored form is "which blocks are disabled", so
    there is no single value to print and each state has to be tested for. A row
    that only printed the enabled case would leave disabled blocks invisible --
    exactly the ones an admin is looking for."""
    label = row["label"]
    if row["type"] == "block":
        block = row["block"]
        return [
            f'execute unless data storage ra:settings disabled[{{b:"{block}"}}] run '
            f'tellraw @s [{{text:"  {label}: ",color:"white"}},{{text:"enabled",color:"green"}}]',
            f'execute if data storage ra:settings disabled[{{b:"{block}"}}] run '
            f'tellraw @s [{{text:"  {label}: ",color:"white"}},{{text:"disabled",color:"red"}}]',
        ]
    path = ppath(row["block"], row["prop"]) if row["type"] == "prop" else gpath(row["key"])
    return [
        f'tellraw @s [{{text:"  {label}: ",color:"white"}},'
        f'{{nbt:"{esc(path)}",storage:"ra:settings",color:"aqua"}}]'
    ]


def _snbt(obj):
    """JSON is not SNBT: SNBT keys are bare and its strings are double-quoted."""
    if isinstance(obj, dict):
        return "{" + ",".join(f"{k}:{_snbt(v)}" for k, v in obj.items()) + "}"
    if isinstance(obj, list):
        return "[" + ",".join(_snbt(v) for v in obj) + "]"
    if isinstance(obj, bool):
        return "1b" if obj else "0b"
    if isinstance(obj, str):
        return json.dumps(obj)
    return str(obj)
